[package]
name = "trajectory-of-a-projectile"
version = "0.1.0"
authors = ["brkydnc <lembervideo12@gmail.com>"]

[dependencies]
piston2d-opengl_graphics = "0.53.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.47.0"
piston_window = "0.80.0"
piston = "0.37.0"
vecmath = "0.3.1"